#!/bin/bash

DAEMON=/opt/web2py/applications/init/actiond/actiond.py
DAEMON_BASE=$(basename $DAEMON)

function status {
	pgrep $DAEMON_BASE >/dev/null 2>&1
}

case $1 in
restart)
	killall -9 $DAEMON_BASE
	sleep 1
	su - collector -c $DAEMON
	;;
start)
	status && {
		echo "already started"
		exit 0
	}
	su - collector -c $DAEMON
	;;
stop)
	killall -9 $DAEMON_BASE
	;;
info)
	echo "Name: actiond"
	;;
status)
	status
	exit $?
	;;
*)
	echo "unsupported action: $1" >&2
	exit 1
	;;
esac
