#!/bin/bash

DAEMON=/opt/web2py/applications/init/actiond/actiond.py
DAEMON_BASE=$(basename $DAEMON)

function status {
	pgrep $DAEMON_BASE >/dev/null 2>&1
}

function run {
	if [ "$(id -un)" == "collector" ]
	then
		$*
	else
		su - collector -c "$*"
	fi
}

case $1 in
restart)
	pkill -9 -f $DAEMON
	sleep 1
	run "python2.7 $DAEMON"
	;;
start)
	status && {
		echo "already started"
		exit 0
	}
	run "python2.7 $DAEMON"
	;;
stop)
	pkill -9 -f $DAEMON
	;;
info)
	echo "Name: actiond"
	;;
status)
	status
	exit $?
	;;
*)
	echo "unsupported action: $1" >&2
	exit 1
	;;
esac
