#!/bin/bash

DAEMON=/opt/web2py/applications/init/alertd/alertd.py
DAEMON_BASE=$(basename $DAEMON)

function status {
	pgrep $DAEMON_BASE >/dev/null 2>&1
}

case $1 in
restart)
	killall $DAEMON_BASE
	su - collector -c "python2.7 $DAEMON"
	;;
start)
	status && {
		echo "already started"
		exit 0
	}
	su - collector "python2.7 $DAEMON"
	;;
stop)
	killall $DAEMON_BASE
	;;
info)
	echo "Name: alertd"
	;;
status)
	status
	exit $?
	;;
*)
	echo "unsupported action: $1" >&2
	exit 1
	;;
esac
