#!/bin/bash

DAEMON=/opt/web2py/applications/init/alertd/alertd.py

function status {
	pgrep -f "$DAEMON" >/dev/null 2>&1
}

case $1 in
restart)
	pkill -f "$DAEMON"
	su - collector -c "$DAEMON"
	;;
start)
	status && {
		echo "already started"
		exit 0
	}
	su - collector -c "$DAEMON"
	;;
stop)
	pkill -f "$DAEMON"
	;;
info)
	echo "Name: alertd"
	;;
status)
	status
	exit $?
	;;
*)
	echo "unsupported action: $1" >&2
	exit 1
	;;
esac

