#!/bin/bash

DAEMON=/opt/web2py/web2py.py
ARGS="-S feed/default/feed_dequeue -M"

function status {
	pgrep -f "$DAEMON $ARGS" >/dev/null 2>&1
}

function stop {
	pkill -f "$DAEMON $ARGS"
}

function start {
	nohup $DAEMON $ARGS >/var/log/feed_queue.log 2>&1 &
}

case $1 in
restart)
	stop
	start
	;;
start)
	status && {
		echo "already started"
		exit 0
	}
	start
	;;
stop)
	stop
	;;
info)
	echo "Name: feed_queue"
	;;
status)
	status
	exit $?
	;;
*)
	echo "unsupported action: $1" >&2
	exit 1
	;;
esac
