#!/bin/bash

SCHED_BIN=/opt/web2py/web2py.py
SCHED_ARGS=${SCHED_ARGS:-"-v -K init,init:janitor,init:metrics,init:slow"}
TASK_RQS==${TASK_RQS:-"feed/default/task_rq_svcmon feed/default/task_rq_svcactions feed/default/task_rq_storage feed/default/task_rq_dashboard feed/default/task_rq_generic init/rest/task_rq_form_submit init/rest/task_rq_async"}


function status_scheduler {
	pgrep -f "$SCHED_BIN $SCHED_ARGS" >/dev/null 2>&1
}

function stop_scheduler {
	pkill -9 -f "$SCHED_BIN $SCHED_ARGS"
}

function start_scheduler {
	status_scheduler && {
		echo "scheduler already started"
		return 0
	}
	cleanup
	nohup su - collector -c "python2.7 $SCHED_BIN $SCHED_ARGS" >/var/log/scheduler.log 2>&1 &
}

function cleanup {
	su - collector -c "python2.7 $SCHED_BIN -S feed/default/scheduler_cleanup"
}

function status_rq {
	pgrep -f "$SCHED_BIN -S $1" >/dev/null 2>&1
}

function start_rq {
	status_rq $1 && {
		echo "redis queue '$1' already started"
		return 0
	}
	nohup su - collector -c "python2.7 $SCHED_BIN -S $1" >/dev/null 2>&1 &
}

function stop_rq {
	pkill -9 -f "python2.7 $SCHED_BIN -S $1"
}

function status_rqs {
	typeset -i r=0
	for RQ in $TASK_RQS
	do
		status_rq $RQ || r=r+1
	done
	return r
}

function start_rqs {
	for RQ in $TASK_RQS
	do
		start_rq $RQ
	done
}

function stop_rqs {
	for RQ in $TASK_RQS
	do
		stop_rq $RQ
	done
}

function print_status {
	[ $1 -eq 0 ] && echo -n "running" || echo -n "stopped"
}

function status {
	typeset -i gr=0
	typeset -i r=0
	status_scheduler
	r=$?
	gr=gr+$r
	echo "scheduler $(print_status $r)"
	for RQ in $TASK_RQS
	do
		status_rq $RQ
		r=$?
		gr=gr+$r
		echo "redis queue '$RQ' $(print_status $r)"
	done
	return $gr
}

case $1 in
restart)
	stop_scheduler
	stop_rqs
	start_scheduler
	start_rqs
	;;
start_rqs)
	start_rqs
	;;
stop_rqs)
	stop_rqs
	;;
start_scheduler)
	start_scheduler
	;;
stop_scheduler)
	stop_scheduler
	;;
start)
	start_scheduler
	start_rqs
	;;
stop)
	stop_scheduler
	stop_rqs
	;;
cleanup)
	cleanup
	;;
info)
	echo "Name: feed_queue"
	;;
status)
	status
	exit $?
	;;
*)
	echo "unsupported action: $1" >&2
	echo "supported actions: restart start_rqs stop_rqs start_scheduler stop_scheduler start stop cleanup info status" >&2
	exit 1
	;;
esac

