#!/bin/bash

DAEMON=/opt/web2py/web2py.py
ARGS="-v -K init,init:janitor,init:storage,init:metrics,init:slow,init:svcmon_1,init:svcmon_2,init:generic_1,init:generic_2,init:dashboard,init:svcactions"

function status {
	pgrep -f "$DAEMON $ARGS" >/dev/null 2>&1
}

function stop {
	pkill -9 -f "$DAEMON $ARGS"
}

function start {
	nohup su - collector -c "python2.7 $DAEMON $ARGS" >/var/log/scheduler.log 2>&1 &
}

function cleanup {
	su - collector -c "python2.7 $DAEMON -S feed/default/scheduler_cleanup"
}

case $1 in
restart)
	stop
	cleanup
	start
	;;
start)
	status && {
		echo "already started"
		exit 0
	}
	cleanup
	start
	;;
stop)
	stop
	;;
cleanup)
	cleanup
	;;
info)
	echo "Name: feed_queue"
	;;
status)
	status
	exit $?
	;;
*)
	echo "unsupported action: $1" >&2
	exit 1
	;;
esac

